# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import nhanvien as nv


class Ui_MainWindow(object):   
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 500)
                MainWindow.setAutoFillBackground(False)
                self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
                self.centralwidget.setStyleSheet("\n"
        "background-color: rgb(248, 255, 243);")
                self.centralwidget.setObjectName("centralwidget")
                self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.gridLayout.setObjectName("gridLayout")
                self.widget = QtWidgets.QWidget(parent=self.centralwidget)
                self.widget.setStyleSheet("QWidget{\n"
        "    background-color: rgb(133, 255, 246);\n"
        "}\n"
        "\n"
        "QPushButton{\n"
        "    height:30px;\n"
        "    border:none;\n"
        "    border-radius:10px;\n"
        "}\n"
        "QPushButton:checked{\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    font-weight:bold;\n"
        "}")
                self.widget.setObjectName("widget")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.label_2 = QtWidgets.QLabel(parent=self.widget)
                self.label_2.setMinimumSize(QtCore.QSize(40, 40))
                self.label_2.setMaximumSize(QtCore.QSize(40, 40))
                self.label_2.setText("")
                self.label_2.setPixmap(QtGui.QPixmap("img/house-chimney-window-solid.png"))
                self.label_2.setScaledContents(True)
                self.label_2.setObjectName("label_2")
                self.verticalLayout_3.addWidget(self.label_2)
                self.verticalLayout = QtWidgets.QVBoxLayout()
                self.verticalLayout.setContentsMargins(0, 15, -1, 0)
                self.verticalLayout.setSpacing(15)
                self.verticalLayout.setObjectName("verticalLayout")
                self.iconHome = QtWidgets.QPushButton(parent=self.widget)
                self.iconHome.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("img/dashboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.iconHome.setIcon(icon)
                self.iconHome.setIconSize(QtCore.QSize(20, 20))
                self.iconHome.setCheckable(True)
                self.iconHome.setAutoExclusive(True)
                self.iconHome.setObjectName("iconHome")
                self.verticalLayout.addWidget(self.iconHome)
                self.iconCustomer = QtWidgets.QPushButton(parent=self.widget)
                self.iconCustomer.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("img/user-group-solid.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.iconCustomer.setIcon(icon1)
                self.iconCustomer.setIconSize(QtCore.QSize(20, 20))
                self.iconCustomer.setCheckable(True)
                self.iconCustomer.setAutoExclusive(True)
                self.iconCustomer.setObjectName("iconCustomer")
                self.verticalLayout.addWidget(self.iconCustomer)
                self.iconPets = QtWidgets.QPushButton(parent=self.widget)
                self.iconPets.setText("")
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap("img/pets.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.iconPets.setIcon(icon2)
                self.iconPets.setIconSize(QtCore.QSize(20, 20))
                self.iconPets.setCheckable(True)
                self.iconPets.setAutoExclusive(True)
                self.iconPets.setObjectName("iconPets")
                self.verticalLayout.addWidget(self.iconPets)
                self.iconEmployee = QtWidgets.QPushButton(parent=self.widget)
                self.iconEmployee.setText("")
                icon3 = QtGui.QIcon()
                icon3.addPixmap(QtGui.QPixmap("img/employee.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.iconEmployee.setIcon(icon3)
                self.iconEmployee.setIconSize(QtCore.QSize(20, 20))
                self.iconEmployee.setCheckable(True)
                self.iconEmployee.setAutoExclusive(True)
                self.iconEmployee.setObjectName("iconEmployee")
                self.verticalLayout.addWidget(self.iconEmployee)
                self.iconChart = QtWidgets.QPushButton(parent=self.widget)
                self.iconChart.setText("")
                icon4 = QtGui.QIcon()
                icon4.addPixmap(QtGui.QPixmap("img/chart.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.iconChart.setIcon(icon4)
                self.iconChart.setIconSize(QtCore.QSize(20, 20))
                self.iconChart.setCheckable(True)
                self.iconChart.setAutoExclusive(True)
                self.iconChart.setObjectName("iconChart")
                self.verticalLayout.addWidget(self.iconChart)
                self.verticalLayout_3.addLayout(self.verticalLayout)
                spacerItem = QtWidgets.QSpacerItem(20, 133, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
                self.verticalLayout_3.addItem(spacerItem)
                self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
                self.pushButton_5.setText("")
                icon5 = QtGui.QIcon()
                icon5.addPixmap(QtGui.QPixmap("img/off.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.pushButton_5.setIcon(icon5)
                self.pushButton_5.setCheckable(True)
                self.pushButton_5.setObjectName("pushButton_5")
                self.verticalLayout_3.addWidget(self.pushButton_5)
                self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
                self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
                self.widget_2.setEnabled(True)
                font = QtGui.QFont()
                font.setPointSize(8)
                self.widget_2.setFont(font)
                self.widget_2.setStyleSheet("QWidget{\n"
        "    background-color: rgb(133, 255, 246);\n"
        "}\n"
        "\n"
        "QPushButton{\n"
        "    height:30px;\n"
        "    border:none;\n"
        "    text-align:left;\n"
        "    padding-left:5px;\n"
        "    padding-right:5px;\n"
        "    border-top-left-radius:10px;\n"
        "    border-bottom-left-radius:10px;\n"
        "}\n"
        "QPushButton:checked{\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    font-weight:bold;\n"
        "}\n"
        "")
                self.widget_2.setObjectName("widget_2")
                self.widget_2.setHidden(True)
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
                self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setContentsMargins(-1, -1, 10, -1)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
                self.label_3.setMinimumSize(QtCore.QSize(40, 40))
                self.label_3.setMaximumSize(QtCore.QSize(40, 40))
                self.label_3.setText("")
                self.label_3.setPixmap(QtGui.QPixmap("img/house-chimney-window-solid.png"))
                self.label_3.setScaledContents(True)
                self.label_3.setObjectName("label_3")
                self.horizontalLayout.addWidget(self.label_3)
                spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
                self.horizontalLayout.addItem(spacerItem1)
                self.label = QtWidgets.QLabel(parent=self.widget_2)
                font = QtGui.QFont()
                font.setPointSize(16)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setObjectName("label")
                self.horizontalLayout.addWidget(self.label)
                self.verticalLayout_4.addLayout(self.horizontalLayout)
                self.verticalLayout_2 = QtWidgets.QVBoxLayout()
                self.verticalLayout_2.setContentsMargins(10, 15, -1, -1)
                self.verticalLayout_2.setSpacing(15)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.btnHome = QtWidgets.QPushButton(parent=self.widget_2)
                self.btnHome.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
                self.btnHome.setAutoFillBackground(False)
                self.btnHome.setIcon(icon)
                self.btnHome.setIconSize(QtCore.QSize(20, 20))
                self.btnHome.setCheckable(True)
                self.btnHome.setAutoExclusive(True)
                self.btnHome.setObjectName("btnHome")
                self.verticalLayout_2.addWidget(self.btnHome)
                self.btnCustomer = QtWidgets.QPushButton(parent=self.widget_2)
                self.btnCustomer.setIcon(icon1)
                self.btnCustomer.setIconSize(QtCore.QSize(20, 20))
                self.btnCustomer.setCheckable(True)
                self.btnCustomer.setAutoExclusive(True)
                self.btnCustomer.setObjectName("btnCustomer")
                self.verticalLayout_2.addWidget(self.btnCustomer)
                self.btnPets = QtWidgets.QPushButton(parent=self.widget_2)
                self.btnPets.setIcon(icon2)
                self.btnPets.setIconSize(QtCore.QSize(20, 20))
                self.btnPets.setCheckable(True)
                self.btnPets.setAutoExclusive(True)
                self.btnPets.setObjectName("btnPets")
                self.verticalLayout_2.addWidget(self.btnPets)
                self.btnEmployee = QtWidgets.QPushButton(parent=self.widget_2)
                self.btnEmployee.setIcon(icon3)
                self.btnEmployee.setIconSize(QtCore.QSize(20, 20))
                self.btnEmployee.setCheckable(True)
                self.btnEmployee.setAutoExclusive(True)
                self.btnEmployee.setObjectName("btnEmployee")
                self.verticalLayout_2.addWidget(self.btnEmployee)
                self.btnChart = QtWidgets.QPushButton(parent=self.widget_2)
                self.btnChart.setIcon(icon4)
                self.btnChart.setIconSize(QtCore.QSize(20, 20))
                self.btnChart.setCheckable(True)
                self.btnChart.setAutoExclusive(True)
                self.btnChart.setObjectName("btnChart")
                self.verticalLayout_2.addWidget(self.btnChart)
                self.verticalLayout_4.addLayout(self.verticalLayout_2)
                spacerItem2 = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
                self.verticalLayout_4.addItem(spacerItem2)
                self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget_2)
                self.pushButton_12.setIcon(icon5)
                self.pushButton_12.setCheckable(True)
                self.pushButton_12.setObjectName("pushButton_12")
                self.verticalLayout_4.addWidget(self.pushButton_12)
                self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
                self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
                self.widget_3.setObjectName("widget_3")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
                self.widget_4.setStyleSheet("QPushButton{""border:none;""}")
                self.widget_4.setObjectName("widget_4")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_4)
                self.pushButton_13.setText("")
                icon6 = QtGui.QIcon()
                icon6.addPixmap(QtGui.QPixmap("img/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.pushButton_13.setIcon(icon6)
                self.pushButton_13.setIconSize(QtCore.QSize(20, 20))
                self.pushButton_13.setCheckable(True)
                self.pushButton_13.setChecked(False)
                self.pushButton_13.setObjectName("pushButton_13")
                self.horizontalLayout_2.addWidget(self.pushButton_13)
                spacerItem3 = QtWidgets.QSpacerItem(451, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
                self.horizontalLayout_2.addItem(spacerItem3)
                self.btnAccount = QtWidgets.QPushButton(parent=self.widget_4)
                self.btnAccount.setText("")
                icon7 = QtGui.QIcon()
                icon7.addPixmap(QtGui.QPixmap("img/customer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnAccount.setIcon(icon7)
                self.btnAccount.setIconSize(QtCore.QSize(20, 20))
                self.btnAccount.setObjectName("btnAccount")
                self.horizontalLayout_2.addWidget(self.btnAccount)
                self.verticalLayout_5.addWidget(self.widget_4)
                self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_3)
                self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);border:1px solid black;QLabel{""border:none;""}")
                self.stackedWidget.setObjectName("stackedWidget")
                self.home_Page = QtWidgets.QWidget()
                self.home_Page.setObjectName("home_Page")
                self.label_4 = QtWidgets.QLabel(parent=self.home_Page)
                self.label_4.setGeometry(QtCore.QRect(160, 80, 60, 16))
                self.label_4.setObjectName("label_4")
                self.stackedWidget.addWidget(self.home_Page)
                self.customer_Page = QtWidgets.QWidget()
                self.customer_Page.setObjectName("customer_Page")
                self.label_5 = QtWidgets.QLabel(parent=self.customer_Page)
                self.label_5.setGeometry(QtCore.QRect(240, 110, 60, 16))
                self.label_5.setObjectName("label_5")
                self.stackedWidget.addWidget(self.customer_Page)
                self.pets_Page = QtWidgets.QWidget()
                self.pets_Page.setObjectName("pets_Page")
                self.label_6 = QtWidgets.QLabel(parent=self.pets_Page)
                self.label_6.setGeometry(QtCore.QRect(280, 160, 60, 16))
                self.label_6.setObjectName("label_6")
                self.stackedWidget.addWidget(self.pets_Page)
                self.employee_page = QtWidgets.QWidget()
                ui = nv.Ui_Form()
                ui.setupUi(self.employee_page)
                self.employee_page.setObjectName("employee_page")
                self.stackedWidget.addWidget(self.employee_page)
                self.chart_Page = QtWidgets.QWidget()
                self.chart_Page.setObjectName("chart_Page")
                self.label_8 = QtWidgets.QLabel(parent=self.chart_Page)
                self.label_8.setGeometry(QtCore.QRect(260, 150, 60, 16))
                self.label_8.setObjectName("label_8")
                self.stackedWidget.addWidget(self.chart_Page)
                self.verticalLayout_5.addWidget(self.stackedWidget)
                self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                self.stackedWidget.setCurrentIndex(4)
                self.pushButton_13.toggled['bool'].connect(self.widget_2.setVisible) # type: ignore
                self.pushButton_13.toggled['bool'].connect(self.widget.setHidden) # type: ignore
                self.pushButton_5.toggled['bool'].connect(MainWindow.close) # type: ignore
                self.pushButton_12.toggled['bool'].connect(MainWindow.close) # type: ignore
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Phòng khám thú y"))
                self.label.setText(_translate("MainWindow", "SideBar"))
                self.btnHome.setText(_translate("MainWindow", "Trang chủ"))
                self.btnCustomer.setText(_translate("MainWindow", "Khách hàng"))
                self.btnPets.setText(_translate("MainWindow", "Thú nuôi"))
                self.btnEmployee.setText(_translate("MainWindow", "Nhân viên"))
                self.btnChart.setText(_translate("MainWindow", "Doanh thu"))
                self.pushButton_12.setText(_translate("MainWindow", "Thoát"))
                self.label_4.setText(_translate("MainWindow", "Home"))
                self.label_5.setText(_translate("MainWindow", "Customer"))
                self.label_6.setText(_translate("MainWindow", "Pets"))
                self.label_8.setText(_translate("MainWindow", "Chart"))
                self.eventHandling()
                
        def showHome_Pages(self):
                self.stackedWidget.setCurrentIndex(0)
        
        def showCustomer_Pages(self):
                self.stackedWidget.setCurrentIndex(1)
        
        def showPets_Pages(self):
                self.stackedWidget.setCurrentIndex(2)
        
        def showEmployee_Pages(self):
                self.stackedWidget.setCurrentIndex(3)
                
        def showChart_Pages(self):
                self.stackedWidget.setCurrentIndex(4)
        
        def eventHandling(self):
                self.btnEmployee.clicked.connect(self.showEmployee_Pages)
                self.btnCustomer.clicked.connect(self.showCustomer_Pages)
                self.btnPets.clicked.connect(self.showPets_Pages)
                self.btnChart.clicked.connect(self.showChart_Pages)
                self.btnHome.clicked.connect(self.showHome_Pages)
                self.iconEmployee.clicked.connect(self.showEmployee_Pages)
                self.iconCustomer.clicked.connect(self.showCustomer_Pages)
                self.iconPets.clicked.connect(self.showPets_Pages)
                self.iconChart.clicked.connect(self.showChart_Pages)
                self.iconHome.clicked.connect(self.showHome_Pages)
                


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
