# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(417, 462)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
                MainWindow.setSizePolicy(sizePolicy)
                MainWindow.setMinimumSize(QtCore.QSize(417, 462))
                MainWindow.setMaximumSize(QtCore.QSize(417, 462))
                MainWindow.setStyleSheet("\n"
        "background-repeat: no-repeat;")
                MainWindow.setDocumentMode(False)
                self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
                self.centralwidget.setStyleSheet("")
                self.centralwidget.setObjectName("centralwidget")
                self.widget = QtWidgets.QWidget(parent=self.centralwidget)
                self.widget.setGeometry(QtCore.QRect(0, 0, 417, 462))
                self.widget.setMinimumSize(QtCore.QSize(417, 462))
                self.widget.setStyleSheet("QWidget{\n"
        "    background-image: url(img/login.png);\n"
        "}\n"
        "")
                self.widget.setObjectName("widget")
                self.label = QtWidgets.QLabel(parent=self.widget)
                self.label.setGeometry(QtCore.QRect(80, 40, 251, 61))
                self.label.setStyleSheet("font: 75 40pt \"Futura\";\n"
        "color: rgb(255, 246, 244);")
                self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(parent=self.widget)
                self.label_2.setGeometry(QtCore.QRect(60, 340, 91, 16))
                self.label_2.setStyleSheet("background-image: url(img/login-back.png);\n"
        "")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(parent=self.widget)
                self.label_3.setGeometry(QtCore.QRect(60, 370, 91, 16))
                self.label_3.setStyleSheet("background-image: url(img/login-back.png);\n"
        "")
                self.label_3.setObjectName("label_3")
                self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
                self.lineEdit.setGeometry(QtCore.QRect(170, 340, 181, 21))
                self.lineEdit.setStyleSheet("background-image: url(img/white.png);")
                self.lineEdit.setText("")
                self.lineEdit.setObjectName("lineEdit")
                self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
                self.lineEdit_2.setGeometry(QtCore.QRect(170, 370, 181, 21))
                self.lineEdit_2.setStyleSheet("\n"
        "background-image: url(img/white.png);")
                self.lineEdit_2.setText("")
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.pushButton = QtWidgets.QPushButton(parent=self.widget)
                self.pushButton.setGeometry(QtCore.QRect(80, 410, 113, 32))
                self.pushButton.setStyleSheet("background-image: url(img/login-back.png);\n"
        "border: 1px solid black;\n"
        "border-radius:10px;\n"
        "")
                self.pushButton.setCheckable(True)
                self.pushButton.setDefault(True)
                self.pushButton.setFlat(False)
                self.pushButton.setObjectName("pushButton")
                self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
                self.pushButton_2.setGeometry(QtCore.QRect(220, 410, 113, 32))
                self.pushButton_2.setStyleSheet("background-image: url(img/login-back.png);\n"
        "border: 1px solid black;\n"
        "border-radius:10px;")
                self.pushButton_2.setCheckable(True)
                self.pushButton_2.setObjectName("pushButton_2")
                MainWindow.setCentralWidget(self.centralwidget)
                
                self.retranslateUi(MainWindow)
                self.pushButton_2.toggled['bool'].connect(MainWindow.close) # type: ignore
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label.setText(_translate("MainWindow", "Phòng khám"))
                self.label_2.setText(_translate("MainWindow", "Tên đăng nhập"))
                self.label_3.setText(_translate("MainWindow", "Mật khẩu"))
                self.pushButton.setText(_translate("MainWindow", "Đăng nhập"))
                self.pushButton.enterEvent = self.enter_accept_event
                self.pushButton.leaveEvent = self.leave_accept_event
                self.pushButton_2.setText(_translate("MainWindow", "Huỷ"))
                self.pushButton_2.enterEvent = self.enter_cancel_event
                self.pushButton_2.leaveEvent = self.leave_cancel_event
        
        def enter_accept_event(self, event):
                self.pushButton.setStyleSheet("font-weight:bold;background-image: url(img/login-back.png);\nborder: 2px solid black;\nborder-radius:10px;\n")
                event.accept()
                
        def leave_accept_event(self, event):
                self.pushButton.setStyleSheet("background-image: url(img/login-back.png);\nborder: 1px solid black;\nborder-radius:10px;")  # Xóa bất kỳ styleSheet nào được thiết lập
                event.accept()
                
        def enter_cancel_event(self, event):
                self.pushButton_2.setStyleSheet("font-weight:bold;background-image: url(img/login-back.png);\nborder: 2px solid black;\nborder-radius:10px;\n")
                event.accept()
                
        def leave_cancel_event(self, event):
                self.pushButton_2.setStyleSheet("background-image: url(img/login-back.png);\nborder: 1px solid black;\nborder-radius:10px;")  # Xóa bất kỳ styleSheet nào được thiết lập
                event.accept()
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
