# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_service_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GUI.loaidv import Ui_Dialog
from DAO.service_category_DAO import serviceCategoryDAO
from DAO.serviceDAO import serviceDAO
from DTO.serviceDTO import Service

class Ui_add_service_dialog(object):
    def setupUi(self, add_service_dialog):
        add_service_dialog.setObjectName("add_service_dialog")
        add_service_dialog.resize(497, 410)
        add_service_dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(add_service_dialog)
        self.label.setGeometry(QtCore.QRect(140, 30, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(add_service_dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 100, 391, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtTenDV = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtTenDV.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtTenDV.setFont(font)
        self.txtTenDV.setObjectName("txtTenDV")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtTenDV)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtGia = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtGia.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtGia.setFont(font)
        self.txtGia.setObjectName("txtGia")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtGia)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbLoaiDV = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cbLoaiDV.setMinimumSize(QtCore.QSize(240, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbLoaiDV.setFont(font)
        self.cbLoaiDV.setObjectName("cbLoaiDV")
        self.horizontalLayout_3.addWidget(self.cbLoaiDV)
        self.btnAddCategoryService = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnAddCategoryService.setMinimumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnAddCategoryService.setFont(font)
        self.btnAddCategoryService.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddCategoryService.setStyleSheet("background-color: #9FC899;\n"
"border-radius: 5px;\n"
"border: none;")
        self.btnAddCategoryService.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddCategoryService.setIcon(icon)
        self.btnAddCategoryService.setObjectName("btnAddCategoryService")
        self.horizontalLayout_3.addWidget(self.btnAddCategoryService)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(add_service_dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 310, 391, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSave.setMinimumSize(QtCore.QSize(85, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSave.setStyleSheet("background-color: #BDD5D7;\n"
"border: none;\n"
"border-radius: 5px;\n"
"color: #333")
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCancel.setMinimumSize(QtCore.QSize(85, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnCancel.setFont(font)
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel.setStyleSheet("border-color: #9F9F9F;\n"
"border-radius: 5px;\n"
"color: #333;")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)

        self.retranslateUi(add_service_dialog)
        self.btnCancel.clicked.connect(add_service_dialog.exec) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_service_dialog)

    def retranslateUi(self, add_service_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_service_dialog.setWindowTitle(_translate("add_service_dialog", "Dialog"))
        self.label.setText(_translate("add_service_dialog", "Thêm dịch vụ"))
        self.label_2.setText(_translate("add_service_dialog", "Tên dịch vụ"))
        self.label_3.setText(_translate("add_service_dialog", "Giá"))
        self.label_4.setText(_translate("add_service_dialog", "Loại dịch vụ"))
        self.btnSave.setText(_translate("add_service_dialog", "Thêm"))
        self.btnCancel.setText(_translate("add_service_dialog", "Hủy"))
        self.addItemToCbLoai()
        self.btnAddCategoryService.clicked.connect(self.show_category_service_form)
        self.btnSave.clicked.connect(self.addService)

    def show_category_service_form(self):
        dialog = QtWidgets.QDialog()
        service_category_dialog = Ui_Dialog()
        service_category_dialog.setupUi(dialog)
        dialog.exec_()
        dialog.show()

    def addItemToCbLoai(self):
        dao = serviceCategoryDAO()
        categories = dao.getAllServiceCategories()

        for category in categories:
            self.cbLoaiDV.addItem(f"{category.getMaLoaiDV()} - {category.getTenLoai()}")

    def addService(self):
        dao = serviceDAO()
        tendv = self.txtTenDV.text()
        gia = self.txtGia.text()
        loaidv = self.cbLoaiDV.currentText().split("-")[0]
        service = Service(None, tendv, gia, loaidv)
        dao.insertService(service)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_service_dialog = QtWidgets.QDialog()
    ui = Ui_add_service_dialog()
    ui.setupUi(add_service_dialog)
    add_service_dialog.show()
    sys.exit(app.exec_())
