# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_service_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_service_dialog(object):
    def setupUi(self, add_service_dialog):
        add_service_dialog.setObjectName("add_service_dialog")
        add_service_dialog.resize(400, 276)
        add_service_dialog.setMinimumSize(QtCore.QSize(400, 276))
        add_service_dialog.setMaximumSize(QtCore.QSize(400, 276))
        self.label = QtWidgets.QLabel(add_service_dialog)
        self.label.setGeometry(QtCore.QRect(60, 90, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(add_service_dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 130, 91, 16))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(add_service_dialog)
        self.widget.setGeometry(QtCore.QRect(0, -1, 401, 61))
        self.widget.setStyleSheet("background-color: rgb(0, 255, 244);\n"
"border:1px solid black;")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.txtName = QtWidgets.QLineEdit(add_service_dialog)
        self.txtName.setGeometry(QtCore.QRect(170, 90, 181, 21))
        self.txtName.setObjectName("txtName")
        self.txtPrice = QtWidgets.QLineEdit(add_service_dialog)
        self.txtPrice.setGeometry(QtCore.QRect(170, 130, 181, 21))
        self.txtPrice.setObjectName("txtPrice")
        self.btnAccept = QtWidgets.QPushButton(add_service_dialog)
        self.btnAccept.setGeometry(QtCore.QRect(80, 180, 113, 32))
        self.btnAccept.setCheckable(True)
        self.btnAccept.setObjectName("btnAccept")
        self.btnDeny = QtWidgets.QPushButton(add_service_dialog)
        self.btnDeny.setGeometry(QtCore.QRect(210, 180, 113, 32))
        self.btnDeny.setCheckable(True)
        self.btnDeny.setObjectName("btnDeny")
        self.btnDeny.toggled['bool'].connect(add_service_dialog.close)

        self.retranslateUi(add_service_dialog)
        QtCore.QMetaObject.connectSlotsByName(add_service_dialog)

    def retranslateUi(self, add_service_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_service_dialog.setWindowTitle(_translate("add_service_dialog", "Dialog"))
        self.label.setText(_translate("add_service_dialog", "Tên dịch vụ"))
        self.label_2.setText(_translate("add_service_dialog", "Giá"))
        self.label_4.setText(_translate("add_service_dialog", "THÊM DỊCH VỤ"))
        self.btnAccept.setText(_translate("add_service_dialog", "Xác nhận"))
        self.btnDeny.setText(_translate("add_service_dialog", "Huỷ"))
        # self.btnAccept.clicked.connect(self.addService)

    # def addService(self):
    #     tendv = self.txtName.text()
    #     gia = self.txtPrice.text()

    #     if not tendv or not gia:
    #         print(f"{tendv} {gia}")
    #         msg.show_warning_messagebox("Vui lòng nhập đầy đủ thông tin") 
    #         return
        
    #     if not gia.isnumeric():
    #         msg.show_warning_messagebox("Vui lòng chỉ nhập số cho trường giá")
    #         return

    #     dao = serviceDAO()
    #     service = Service(None, tendv, gia)
    #     dao.insertService(service)  
    #     msg.show_info_messagebox("Thêm dịch vụ thành công!")
    #     Ui_MainWindow.loadServiceData()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_service_dialog = QtWidgets.QDialog()
    ui = Ui_add_service_dialog()
    ui.setupUi(add_service_dialog)
    add_service_dialog.show()
    sys.exit(app.exec_())
