# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cameraTN.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QPixmap,QImage
import numpy as np
from PIL import ImageFont, ImageDraw, Image
from keras.models import load_model
import cv2
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from DAO.petDAO import petDAO

class Ui_Form(object):
    def setupUi(self, Form):
        
        self.parent_directory = 'data/thunuoi'
        self.model = load_model('model/modelTN.h5')
        
        self.camera = cv2.VideoCapture(1)
        
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_frame)
        self.timer.start(50)
        
        self.class_names = os.listdir(self.parent_directory)
        
        Form.setObjectName("Form")
        Form.resize(800, 550)
        Form.setMaximumSize(QtCore.QSize(800, 550))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 510))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(180, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.close_dialog)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Nhận diện"))
        self.pushButton.setText(_translate("Form", "Xong"))
        
    
    def update_frame(self):
        self.face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
        ret, frame = self.camera.read()
        if ret:
            # Chuyển đổi hình ảnh từ BGR sang RGB để hiển thị trong PyQt5
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame_rgb = cv2.resize(frame_rgb,(120,120))
            
            frame_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
                
            draw = ImageDraw.Draw(frame_pil)
                
            font = ImageFont.truetype("Arial.ttf", 30)
            
            prediction = self.model.predict(np.expand_dims(frame_rgb, axis=0))
            
            if prediction.max() < 0.6:
                self.id = None
                color = (255,0,0)
                draw.text((10, 10), "Unknown", font=font, fill=color)
            else:
                self.id = self.class_names[int(np.argmax(prediction))]
                tn = petDAO()
                pet = tn.findById1(self.id)
                color = (0,255,0)
                draw.text((10, 10), f'Tên: {pet.get_tentn()}', font=font, fill=color) 
                draw.text((10, 40), f'Màu lông: {pet.get_maulong()}', font=font, fill=color) 
                draw.text((10, 70), f'Cân nặng: {pet.get_cannang()}', font=font, fill=color)
                draw.text((10, 100), f'Thuộc khách: {pet.get_khachhang().get_tenkh()}', font=font, fill=color)
            
            frame_with_text = cv2.cvtColor(np.array(frame_pil), cv2.COLOR_RGB2BGR)
            frame_rgb = cv2.cvtColor(frame_with_text, cv2.COLOR_BGR2RGB)
            
            
            image = QImage(frame_rgb.data, frame_rgb.shape[1], frame_rgb.shape[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(image)
            
            self.label.setPixmap(pixmap)
            
    def close_dialog(self):
        self.camera.release()
        self.Dialog.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
