# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ctpn_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ctpn_dialog(object):
    def setupUi(self, ctpn_dialog):
        ctpn_dialog.setObjectName("ctpn_dialog")
        ctpn_dialog.resize(400, 304)
        ctpn_dialog.setMinimumSize(QtCore.QSize(400, 276))
        self.label = QtWidgets.QLabel(ctpn_dialog)
        self.label.setGeometry(QtCore.QRect(50, 110, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ctpn_dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 111, 16))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(ctpn_dialog)
        self.widget.setGeometry(QtCore.QRect(0, -1, 401, 61))
        self.widget.setStyleSheet("background-color: rgb(0, 255, 244);\n"
"border:1px solid black;")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btnAccept = QtWidgets.QPushButton(ctpn_dialog)
        self.btnAccept.setGeometry(QtCore.QRect(70, 240, 113, 32))
        self.btnAccept.setCheckable(True)
        self.btnAccept.setObjectName("btnAccept")
        self.btnDeny = QtWidgets.QPushButton(ctpn_dialog)
        self.btnDeny.setGeometry(QtCore.QRect(200, 240, 113, 32))
        self.btnDeny.setCheckable(True)
        self.btnDeny.setObjectName("btnDeny")
        self.cbMaDP = QtWidgets.QComboBox(ctpn_dialog)
        self.cbMaDP.setGeometry(QtCore.QRect(170, 110, 181, 22))
        self.cbMaDP.setObjectName("cbMaDP")
        self.txtPrice = QtWidgets.QLineEdit(ctpn_dialog)
        self.txtPrice.setEnabled(False)
        self.txtPrice.setGeometry(QtCore.QRect(170, 150, 181, 22))
        self.txtPrice.setReadOnly(False)
        self.txtPrice.setObjectName("txtPrice")
        self.txtQty = QtWidgets.QLineEdit(ctpn_dialog)
        self.txtQty.setGeometry(QtCore.QRect(170, 190, 181, 22))
        self.txtQty.setObjectName("txtQty")
        self.label_3 = QtWidgets.QLabel(ctpn_dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 111, 16))
        self.label_3.setObjectName("label_3")
        self.btnDeny.toggled['bool'].connect(ctpn_dialog.close)

        self.retranslateUi(ctpn_dialog)
        QtCore.QMetaObject.connectSlotsByName(ctpn_dialog)

    def retranslateUi(self, ctpn_dialog):
        _translate = QtCore.QCoreApplication.translate
        ctpn_dialog.setWindowTitle(_translate("ctpn_dialog", "Dialog"))
        self.label.setText(_translate("ctpn_dialog", "Mã dược phẩm"))
        self.label_2.setText(_translate("ctpn_dialog", "Giá"))
        self.label_4.setText(_translate("ctpn_dialog", "THÊM CTPN"))
        self.btnAccept.setText(_translate("ctpn_dialog", "Xác nhận"))
        self.btnDeny.setText(_translate("ctpn_dialog", "Huỷ"))
        self.label_3.setText(_translate("ctpn_dialog", "Số lượng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ctpn_dialog = QtWidgets.QDialog()
    ui = Ui_ctpn_dialog()
    ui.setupUi(ctpn_dialog)
    ctpn_dialog.show()
    sys.exit(app.exec_())
