# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dichvu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DAO.serviceDAO import serviceDAO

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(7)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: #BDD5D7;\n"
"    border:1px solid black\n"
"}\n"
"QLabel{\n"
"    border:none\n"
"}\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setContentsMargins(11, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(8, 5, 8, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(self.widget_3)
        self.btnAdd.setMinimumSize(QtCore.QSize(90, 40))
        self.btnAdd.setStyleSheet("background-color: #9FC899;\n"
"border: none;\n"
"border-radius: 5px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon)
        self.btnAdd.setIconSize(QtCore.QSize(20, 20))
        self.btnAdd.setFlat(False)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnDelete = QtWidgets.QPushButton(self.widget_3)
        self.btnDelete.setMinimumSize(QtCore.QSize(90, 40))
        self.btnDelete.setStyleSheet("background-color: rgb(255, 124, 125);\n"
"border: none;\n"
"border-radius: 5px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon1)
        self.btnDelete.setIconSize(QtCore.QSize(20, 20))
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.btnUpdate = QtWidgets.QPushButton(self.widget_3)
        self.btnUpdate.setMinimumSize(QtCore.QSize(90, 40))
        self.btnUpdate.setStyleSheet("background-color: rgb(188, 202, 255);\n"
"border: none;\n"
"border-radius: 5px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpdate.setIcon(icon2)
        self.btnUpdate.setIconSize(QtCore.QSize(20, 20))
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout.addWidget(self.btnUpdate)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_3, 2, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(8, 5, 8, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.input_search = QtWidgets.QLineEdit(self.widget_2)
        self.input_search.setObjectName("input_search")
        self.horizontalLayout_2.addWidget(self.input_search)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.btnSearch = QtWidgets.QPushButton(self.widget_2)
        self.btnSearch.setMinimumSize(QtCore.QSize(90, 40))
        self.btnSearch.setStyleSheet("background-color: #BDD5D7;\n"
"border: none;\n"
"border-radius: 5px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSearch.setIcon(icon3)
        self.btnSearch.setIconSize(QtCore.QSize(20, 20))
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_2.addWidget(self.btnSearch)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.table_service = QtWidgets.QTableWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_service.sizePolicy().hasHeightForWidth())
        self.table_service.setSizePolicy(sizePolicy)
        self.table_service.setWordWrap(False)
        self.table_service.setColumnCount(4)
        self.table_service.setObjectName("table_service")
        self.table_service.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_service.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_service.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_service.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_service.setHorizontalHeaderItem(3, item)
        self.table_service.horizontalHeader().setCascadingSectionResizes(False)
        self.table_service.horizontalHeader().setSortIndicatorShown(False)
        self.table_service.horizontalHeader().setStretchLastSection(True)
        self.table_service.verticalHeader().setVisible(False)
        self.table_service.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.table_service)
        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Quản lý dịch vụ"))
        self.btnAdd.setText(_translate("Form", "Thêm"))
        self.btnDelete.setText(_translate("Form", "Xoá"))
        self.btnUpdate.setText(_translate("Form", "Sửa"))
        self.label_2.setText(_translate("Form", "Tìm kiếm "))
        self.btnSearch.setText(_translate("Form", "Tìm"))
        self.table_service.setSortingEnabled(False)
        item = self.table_service.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mã dịch vụ"))
        item = self.table_service.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên dịch vụ"))
        item = self.table_service.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Giá"))
        item = self.table_service.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Loại dịch vụ"))
        self.loadServiceData()

    def loadServiceData(self):
        dao =serviceDAO()
        services = dao.getAllServices()
        row = 0
        self.table_service.setRowCount(len(services))
        for service in services:
            self.table_service.setItem(row, 0, QtWidgets.QTableWidgetItem(str(service.getMaDV())))
            self.table_service.setItem(row, 1, QtWidgets.QTableWidgetItem(service.getTen()))
            self.table_service.setItem(row, 2, QtWidgets.QTableWidgetItem(str(service.getGia())))
            self.table_service.setItem(row, 3, QtWidgets.QTableWidgetItem(str(service.getMaLoaiDV())))
            row = row +1



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
