# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/doimk.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from DAO.taikhoanDAO import taikhoanDAO
import GUI.thongbao as tb

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.tb = tb.Ui_Dialog()
        self.tkDAO = taikhoanDAO()
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 300)
        Dialog.setMinimumSize(QtCore.QSize(420, 300))
        Dialog.setMaximumSize(QtCore.QSize(420, 300))
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 421, 71))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(65, 255, 245);\n"
"    border:1px solid black\n"
"}\n"
"QLabel{\n"
"         border:none\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(100, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 91, 16))
        self.label_2.setObjectName("label_2")
        self.manv = QtWidgets.QLabel(Dialog)
        self.manv.setObjectName("manv")
        self.manv.setVisible(False)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 190, 111, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(180, 110, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setEchoMode(QLineEdit.Password)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 150, 201, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QLineEdit.Password)
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 190, 201, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setEchoMode(QLineEdit.Password)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 240, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.doiMK)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 240, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ĐỔI MẬT KHẨU"))
        self.label_2.setText(_translate("Dialog", "Mật khẩu cũ"))
        self.label_3.setText(_translate("Dialog", "Mật khẩu mới"))
        self.label_4.setText(_translate("Dialog", "Nhập lại mật khẩu"))
        self.pushButton.setText(_translate("Dialog", "Xác nhận"))
        self.pushButton_2.setText(_translate("Dialog", "Huỷ"))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.toggled['bool'].connect(Dialog.close)
    
    def doiMK(self):
        oldPass = self.lineEdit.text()
        newPass = self.lineEdit_2.text()
        reNewPass = self.lineEdit_3.text()
        manv = self.manv.text()
        check = self.tkDAO.checkOldPass(manv,oldPass)
        if check is not None:
            self.tb.thongBao(self.tkDAO.doiMK(check,newPass,reNewPass))
        else:
            self.tb.thongBao("Mật khẩu cũ nhập không đúng !!!!")
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")
        


