# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/slideshow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1127, 696)
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("#widget {\n"
"    image: url(img/background.jpg);\n"
"    border: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_prev = QtWidgets.QPushButton(self.frame)
        self.btn_prev.setStyleSheet("#btn_prev {\n"
"    border: none;\n"
"    width: 40px;\n"
"    height: 300px;\n"
"    qproperty-iconSize: 60px;\n"
"}\n"
"#btn_prev:hover {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #777777;\n"
"}")
        self.btn_prev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../img/Back_50px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon)
        self.btn_prev.setObjectName("btn_prev")
        self.gridLayout_2.addWidget(self.btn_prev, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_next = QtWidgets.QPushButton(self.frame_2)
        self.btn_next.setStyleSheet("#btn_next {\n"
"    border: none;\n"
"    width: 40px;\n"
"    height: 300px;\n"
"    qproperty-iconSize: 60px;\n"
"}\n"
"#btn_next:hover {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #777777;\n"
"}")
        self.btn_next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../img/next_50px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon1)
        self.btn_next.setObjectName("btn_next")
        self.gridLayout_3.addWidget(self.btn_next, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 2, 2, 1)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_bottom_1 = QtWidgets.QPushButton(self.frame_3)
        self.btn_bottom_1.setStyleSheet("#btn_bottom_1 {\n"
"    border: none;\n"
"    background-color: #777777;\n"
"    height: 5px;\n"
"    width: 30px;\n"
"}\n"
"#btn_bottom_1:checked {\n"
"    background-color: #fff;\n"
"}")
        self.btn_bottom_1.setText("")
        self.btn_bottom_1.setCheckable(True)
        self.btn_bottom_1.setAutoExclusive(True)
        self.btn_bottom_1.setObjectName("btn_bottom_1")
        self.horizontalLayout.addWidget(self.btn_bottom_1)
        self.btn_bottom_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_bottom_2.setStyleSheet("#btn_bottom_2 {\n"
"    border: none;\n"
"    background-color: #777777;\n"
"    height: 5px;\n"
"    width: 30px;\n"
"}\n"
"#btn_bottom_2:checked {\n"
"    background-color: #fff;\n"
"}")
        self.btn_bottom_2.setText("")
        self.btn_bottom_2.setCheckable(True)
        self.btn_bottom_2.setAutoExclusive(True)
        self.btn_bottom_2.setObjectName("btn_bottom_2")
        self.horizontalLayout.addWidget(self.btn_bottom_2)
        self.btn_bottom_3 = QtWidgets.QPushButton(self.frame_3)
        self.btn_bottom_3.setStyleSheet("#btn_bottom_3 {\n"
"    border: none;\n"
"    background-color: #777777;\n"
"    height: 5px;\n"
"    width: 30px;\n"
"}\n"
"#btn_bottom_3:checked {\n"
"    background-color: #fff;\n"
"}")
        self.btn_bottom_3.setText("")
        self.btn_bottom_3.setCheckable(True)
        self.btn_bottom_3.setAutoExclusive(True)
        self.btn_bottom_3.setObjectName("btn_bottom_3")
        self.horizontalLayout.addWidget(self.btn_bottom_3)
        spacerItem1 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.frame_3, 1, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("border: none;")
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("border: none;")
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("border: none;")
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.page.setAccessibleDescription(_translate("Form", "background-color: transparent;"))
        self.page_3.setAccessibleDescription(_translate("Form", "background-color: transparent;"))
        self.page_2.setAccessibleDescription(_translate("Form", "background-color: transparent;"))
        self.stackedWidget.setCurrentIndex(0)
        self.btn_bottom_1.setChecked(True)
        self.btn_next.clicked.connect(self.next_page)
        self.btn_prev.clicked.connect(self.prev_page)

    def next_page(self):
        current_index = self.stackedWidget.currentIndex()

        if current_index == self.stackedWidget.count() - 1:
            self.stackedWidget.setCurrentIndex(0)
        else:
            self.stackedWidget.setCurrentIndex(current_index + 1)

        index = self.stackedWidget.currentIndex()
        self.change_background_img(index)

    def prev_page(self):
        current_index = self.stackedWidget.currentIndex()

        if current_index == 0:
            self.stackedWidget.setCurrentIndex(self.stackedWidget.count() - 1)
        else:
            self.stackedWidget.setCurrentIndex(current_index - 1)

        index = self.stackedWidget.currentIndex()
        self.change_background_img(index)

    def change_background_img(self, index):
        print(index)
        if index == 0:
            self.widget.setStyleSheet("#widget {image: url(img/background.jpg);}")
            self.btn_bottom_1.setChecked(True)
        elif index == 1:
            self.widget.setStyleSheet("#widget {image: url(img/background2.jpg);}")
            self.btn_bottom_2.setChecked(True)
        else:
            self.widget.setStyleSheet("#widget {image: url(img/background3.png);}")
            self.btn_bottom_3.setChecked(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
