# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(488, 488)
        self.widget = QtWidgets.QWidget(login_form)
        self.widget.setGeometry(QtCore.QRect(30, 10, 417, 462))
        self.widget.setMinimumSize(QtCore.QSize(417, 462))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(80, 40, 251, 61))
        self.label.setStyleSheet("font: 75 40pt \"Futura\";\n"
"color: rgb(255, 246, 244);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 340, 91, 16))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/login-back.png);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(60, 370, 91, 16))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/login-back.png);\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 340, 181, 21))
        self.lineEdit.setStyleSheet("background-image: url(:/newPrefix/white.png);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 370, 181, 21))
        self.lineEdit_2.setStyleSheet("\n"
"background-image: url(:/newPrefix/white.png);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btnLogin = QtWidgets.QPushButton(self.widget)
        self.btnLogin.setGeometry(QtCore.QRect(80, 410, 113, 32))
        self.btnLogin.setStyleSheet("background-image: url(:/newPrefix/login-back.png);\n"
"border: 1px solid black;\n"
"border-radius:10px;\n"
"")
        self.btnLogin.setCheckable(True)
        self.btnLogin.setDefault(True)
        self.btnLogin.setFlat(False)
        self.btnLogin.setObjectName("btnLogin")
        self.btnCancel = QtWidgets.QPushButton(self.widget)
        self.btnCancel.setGeometry(QtCore.QRect(220, 410, 113, 32))
        self.btnCancel.setStyleSheet("background-image: url(:/newPrefix/login-back.png);\n"
"border: 1px solid black;\n"
"border-radius:10px;")
        self.btnCancel.setCheckable(True)
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Form"))
        self.label.setText(_translate("login_form", "Phòng khám"))
        self.label_2.setText(_translate("login_form", "Tên đăng nhập"))
        self.label_3.setText(_translate("login_form", "Mật khẩu"))
        self.btnLogin.setText(_translate("login_form", "Đăng nhập"))
        self.btnCancel.setText(_translate("login_form", "Huỷ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_form = QtWidgets.QWidget()
    ui = Ui_login_form()
    ui.setupUi(login_form)
    login_form.show()
    sys.exit(app.exec_())
