# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/medicine_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_medicine_dialog(object):
    def setupUi(self, medicine_dialog):
        medicine_dialog.setObjectName("medicine_dialog")
        medicine_dialog.resize(400, 358)
        medicine_dialog.setMinimumSize(QtCore.QSize(400, 276))
        self.label = QtWidgets.QLabel(medicine_dialog)
        self.label.setGeometry(QtCore.QRect(50, 90, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(medicine_dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 91, 16))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(medicine_dialog)
        self.widget.setGeometry(QtCore.QRect(0, -1, 401, 61))
        self.widget.setStyleSheet("background-color: rgb(0, 255, 244);\n"
"border:1px solid black;")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.txtName = QtWidgets.QLineEdit(medicine_dialog)
        self.txtName.setGeometry(QtCore.QRect(170, 90, 181, 21))
        self.txtName.setObjectName("txtName")
        self.txtQty = QtWidgets.QLineEdit(medicine_dialog)
        self.txtQty.setGeometry(QtCore.QRect(170, 210, 181, 21))
        self.txtQty.setObjectName("txtQty")
        self.btnAccept = QtWidgets.QPushButton(medicine_dialog)
        self.btnAccept.setGeometry(QtCore.QRect(80, 300, 113, 32))
        self.btnAccept.setCheckable(True)
        self.btnAccept.setObjectName("btnAccept")
        self.btnDeny = QtWidgets.QPushButton(medicine_dialog)
        self.btnDeny.setGeometry(QtCore.QRect(210, 300, 113, 32))
        self.btnDeny.setCheckable(True)
        self.btnDeny.setObjectName("btnDeny")
        self.label_3 = QtWidgets.QLabel(medicine_dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 91, 16))
        self.label_3.setObjectName("label_3")
        self.txtHSD = QtWidgets.QDateEdit(medicine_dialog)
        self.txtHSD.setGeometry(QtCore.QRect(170, 170, 181, 22))
        self.txtHSD.setObjectName("txtHSD")
        self.txtNSX = QtWidgets.QDateEdit(medicine_dialog)
        self.txtNSX.setGeometry(QtCore.QRect(170, 130, 181, 22))
        self.txtNSX.setObjectName("txtNSX")
        self.label_5 = QtWidgets.QLabel(medicine_dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 91, 16))
        self.label_5.setObjectName("label_5")
        self.txtPrice = QtWidgets.QLineEdit(medicine_dialog)
        self.txtPrice.setGeometry(QtCore.QRect(170, 250, 181, 21))
        self.txtPrice.setText("")
        self.txtPrice.setObjectName("txtPrice")
        self.label_6 = QtWidgets.QLabel(medicine_dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 250, 91, 16))
        self.label_6.setObjectName("label_6")
        self.btnDeny.toggled['bool'].connect(medicine_dialog.close)

        self.retranslateUi(medicine_dialog)
        QtCore.QMetaObject.connectSlotsByName(medicine_dialog)

    def retranslateUi(self, medicine_dialog):
        _translate = QtCore.QCoreApplication.translate
        medicine_dialog.setWindowTitle(_translate("medicine_dialog", "Dialog"))
        self.label.setText(_translate("medicine_dialog", "Tên dược phẩm"))
        self.label_2.setText(_translate("medicine_dialog", "Ngày sản xuất"))
        self.label_4.setText(_translate("medicine_dialog", "THÊM DƯỢC PHẨM"))
        self.btnAccept.setText(_translate("medicine_dialog", "Xác nhận"))
        self.btnDeny.setText(_translate("medicine_dialog", "Huỷ"))
        self.label_3.setText(_translate("medicine_dialog", "Hạn sử dụng"))
        self.label_5.setText(_translate("medicine_dialog", "Số lượng"))
        self.label_6.setText(_translate("medicine_dialog", "Giá thành"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    medicine_dialog = QtWidgets.QDialog()
    ui = Ui_medicine_dialog()
    ui.setupUi(medicine_dialog)
    medicine_dialog.show()
    sys.exit(app.exec_())
