# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/TacVuKH.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from DAO.customerDAO import customerDAO
from DTO.customerDTO import customer
import GUI.thongbao as tb


class Ui_Dialog(object):
    def setupUi(self, Dialog,type):
        self.tb = tb.Ui_Dialog()
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 90, 101, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 101, 20))
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, -1, 401, 61))
        self.widget.setStyleSheet("background-color: rgb(0, 255, 244);\n"
"border:1px solid black;")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(100, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.visible = QtWidgets.QLabel(self.widget)
        self.visible.setGeometry(QtCore.QRect(100, 20, 191, 31))
        self.visible.setVisible(False)
        self.txtName = QtWidgets.QLineEdit(Dialog)
        self.txtName.setGeometry(QtCore.QRect(170, 90, 181, 21))
        self.txtName.setObjectName("txtName")
        self.txtPhone = QtWidgets.QLineEdit(Dialog)
        self.txtPhone.setGeometry(QtCore.QRect(170, 130, 181, 21))
        self.txtPhone.setObjectName("txtPhone")
        self.txtEmail = QtWidgets.QLineEdit(Dialog)
        self.txtEmail.setGeometry(QtCore.QRect(170, 170, 181, 21))
        self.txtEmail.setObjectName("txtEmail")
        self.btnAccept = QtWidgets.QPushButton(Dialog)
        self.btnAccept.setGeometry(QtCore.QRect(80, 250, 113, 32))
        self.btnAccept.setCheckable(True)
        self.btnAccept.setObjectName("btnAccept")
        if type == 1:
            self.btnAccept.clicked.connect(self.show_dialog_insert)
        else :
            self.btnAccept.clicked.connect(self.show_dialog_update)
        self.btnDeny = QtWidgets.QPushButton(Dialog)
        self.btnDeny.setGeometry(QtCore.QRect(210, 250, 113, 32))
        self.btnDeny.setCheckable(True)
        self.btnDeny.setObjectName("btnDeny")
        self.btnDeny.toggled['bool'].connect(Dialog.close)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 101, 20))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(170, 210, 131, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Nữ")
        self.comboBox.addItem("Nam")
            

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Tên khách hàng"))
        self.label_2.setText(_translate("Dialog", "Số điện thoại"))
        self.label_3.setText(_translate("Dialog", "Email"))
        self.label_4.setText(_translate("Dialog", "THÊM KHÁCH HÀNG"))
        self.btnAccept.setText(_translate("Dialog", "Xác nhận"))
        self.btnDeny.setText(_translate("Dialog", "Huỷ"))
        self.label_5.setText(_translate("Dialog", "Giới tính"))
        
    def insert_data(self):
        ten=self.txtName.text()
        email=self.txtEmail.text()
        sdt=self.txtPhone.text()
        gioitinh = self.comboBox.currentIndex()
        cusDAO= customerDAO()
        if ten and sdt:
            cus = customer("",ten,gioitinh,sdt,email)
            result = cusDAO.insert(cus)
            if result == "Thêm thành công !!!!":
                self.txtName.setText("")
                self.txtEmail.setText("")
                self.txtPhone.setText("")
                self.comboBox.setCurrentIndex(0)
            return result
            
        else: 
            return 'Tên và số điện thoại không được rỗng !!!!'

    def update_data(self):
        id = self.visible.text()
        ten=self.txtName.text()
        email=self.txtEmail.text()
        sdt=self.txtPhone.text()
        gioitinh = self.comboBox.currentIndex()
        cusDAO= customerDAO()
        if ten and sdt:
            cus = customer(id,ten,gioitinh,sdt,email)
            result = cusDAO.update(cus)
            if result == "Cập nhật thành công !!!!":
                self.txtName.setText("")
                self.txtEmail.setText("")
                self.txtPhone.setText("")
                self.comboBox.setCurrentIndex(0)
            return result
        else: 
            return 'Tên và số điện thoại không được rỗng !!!!'
    
    def show_dialog_update(self):
        self.tb.thongBao(self.update_data())    
        
    def show_dialog_insert(self):
        self.tb.thongBao(self.insert_data())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
