# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/thongtinlogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(7)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(65, 255, 245);\n"
"    border:1px solid black\n"
"}\n"
"QLabel{\n"
"    border:none\n"
"}\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(88)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtMaNV = QtWidgets.QLineEdit(self.widget_2)
        self.txtMaNV.setEnabled(False)
        self.txtMaNV.setMinimumSize(QtCore.QSize(0, 32))
        self.txtMaNV.setObjectName("txtMaNV")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtMaNV)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtTenNV = QtWidgets.QLineEdit(self.widget_2)
        self.txtTenNV.setEnabled(False)
        self.txtTenNV.setMinimumSize(QtCore.QSize(0, 32))
        self.txtTenNV.setObjectName("txtTenNV")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtTenNV)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtSdt = QtWidgets.QLineEdit(self.widget_2)
        self.txtSdt.setEnabled(False)
        self.txtSdt.setMinimumSize(QtCore.QSize(0, 32))
        self.txtSdt.setObjectName("txtSdt")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtSdt)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtEmail = QtWidgets.QLineEdit(self.widget_2)
        self.txtEmail.setEnabled(False)
        self.txtEmail.setMinimumSize(QtCore.QSize(0, 32))
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtEmail)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtMaTK = QtWidgets.QLineEdit(self.widget_2)
        self.txtMaTK.setEnabled(False)
        self.txtMaTK.setMinimumSize(QtCore.QSize(0, 32))
        self.txtMaTK.setObjectName("txtMaTK")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtMaTK)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Thông tin đăng nhập"))
        self.label_2.setText(_translate("Form", "Mã nhân viên"))
        self.label_3.setText(_translate("Form", "Tên nhân viên"))
        self.label_4.setText(_translate("Form", "Số điện thoại"))
        self.label_5.setText(_translate("Form", "Email"))
        self.label_6.setText(_translate("Form", "Mã tài khoản"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
